### ISSUE TITLE
Install fails on "Settings configurations..."

### ISSUE THREAD

**Issue by SecOpsWarrior** [cyberthint/cuckoo-sandbox-basic-setup#2]
Hi there. Just want to say that this script is AWESOME. Thanks for putting this together.

Everything seemed to work perfectly on the run-as-cuckoo.sh script until it goes to set up the vm's and "Settings configurations..." section at the very end. The Host is a Debian 10.9 install running on VMware ESXi 7. I verified virtualbox-ext-pack is installed...what am I missing?

I get the below output:

```
INFO:vmcloak:Starting the Virtual Machine u'win7x64base' to install Windows.
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'startvm', u'win7x64base', '--type', 'headless']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/bin/vmcloak", line 8, in <module>
    sys.exit(main())
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/vmcloak/main.py", line 273, in init
    m.start_vm(visible=vm_visible)
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/vmcloak/vm.py", line 201, in start_vm
    type_="gui" if visible else "headless")
  File "/home/cuckoo/cuckoo/local/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError

>>> Creating cuckoo image from base file...

ERROR:vmcloak:Image not found: win7x64base

>>> Installing packages in cuckoo image...

ERROR:vmcloak:Image not found: win7x64cuckoo

>>> Creating snapshots...

ERROR:vmcloak:Image not found: win7x64cuckoo

>>> Settings configurations...

mv: cannot stat '/home/cuckoo/.cuckoo/conf/': No such file or directory
cp: cannot create directory '/home/cuckoo/.cuckoo/conf': No such file or directory
```

Any ideas on this?

**Comment by serhattsnmz** [comment]
Please make sure;
* Your host virtualization is enabled.
* If you are using Virtualbox, make sure VT-x/AMD-V is enabled.

If you look at your error, you can see that:
```
...
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
...
```

**Comment by SecOpsWarrior** [comment]
Yes, a little more investigation shows that "Hardware Virtualization" must be turned on for the host settings in VMware to allow this to work. However, it seems there is no way to enable this in VMware 7 for a Linux host, because to do this, you must be able to turn off VBS, and controlling that setting is only supported for Windows hosts as of now. Would love if anyone has insight who knows how to force change this setting via config file or the VMWare shell. Any ideas?
